### ISSUE TITLE
Python module not called out as separate datasketches-python repository

### ISSUE THREAD

**Issue by Claudenw** [apache/datasketches-website#177]
There are several places this is an issue.  I opened a Jira issue [DATASKETCHES-13] but see now that the tracking of issues has moved to github.

The component repositories on https://datasketches.apache.org/docs/Architecture/Components.html does not include the python module.  In addition multiple web pages and readme files point to https://github.com/apache/datasketches-cpp/tree/master/python which does not exist.  I have submitted pull requests to fix some of these but a full comb though all the documentation may be necessary.

**Comment by leerho** [comment]
@Claudenw,
Thank you for pointing this out.  Both of the issues you mentioned, missing Python references and the 404s have now been fixed!  

This issue is now closed!
